### ISSUE TITLE
semantic markup

### ISSUE THREAD

**Issue by ghost** [ejvkamp/ColmarAcademy#2]
https://github.com/ejvkamp/ColmarAcademy/blob/master/index.html#L16-L40

Nice job using HTML5 tags like `header`, `nav`, and `footer` to make your markup more semantic 👍 

Consider adding some more semantic tags like: `main`, `section`, `article`, `aside`, `figure`, etc. This is much better than relying constantly on `div` tags, and can make your code much easier to read and reason about.

**Comment by ejvkamp** [comment]
Thanks for the guidance as I'm still new so this helps to know what other tags I can (and should) be using instead of div all the time.
